### ISSUE TITLE
Mapgen generated plant on incorrect nodes when use groups

### ISSUE THREAD

**Issue by paanrama** [minetest-mods/biome_lib#9]
I installed the new versions of biome_lib, plantlife_modpack and moretrees 2 weeks ago, then I begining to create some new plants using in biome definition surface = {"group:soil"}. During mapgen some of the new plants grow over snow, water and silver_sand. 

Before some review of biome_lib code I found that the error seems to disapear when in biome_lib file init.lua row 223 I replace 

if string.find(biome.surface[j], "^group:") 
    and minetest.get_item_group(dest_node.name, biome.surface[j]) then
    surface_ok = true
    break
end

with

if string.find(biome.surface[j], "^group:") then
    local name_parts = biome.surface[j]:split(":")
    if #name_parts >= 2 and name_parts[2] ~= nil then
        if minetest.get_item_group(dest_node.name, name_parts[2]) >= 1 then
            surface_ok = true
            break
        end
    end
end

I not checked if the problem is only with biome_lib:register_generate_plant or it also is found with biome_lib:spawn_on_surfaces.

PD: Sorry with my bad english.

**Comment by VanessaE** [comment]
Groups are not supported for surface defintions.
